### PR TITLE
Update mc-aws-linux2.sh

### PR DESCRIPTION
**Pull request by diogo24m**
Update installation for next nodejs TLS version

### CODE REVIEW

**Comment by si458** [comment]
can it be changed to node 16 at all?
only because a lot of modules NOW require at least node 16

**Comment by diogo24m** [comment]
Yes, already tested with that version
I'll make the changes

Also, I'll change the nvm version based on this aws ec2 guide:
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-up-node-on-ec2-instance.html

**Comment by diogo24m** [comment]
I now noticed that the mongo script is also outdated

**Comment by si458** [comment]
> I now noticed that the mongo script is also outdated

sorry my bad! merged before you was ready! just keep doing PR requests!

**Pull request merged**
